/* This file is generated by scripts/generate-notes-data.py. */

import type { NotesForConsultation } from "./notes";

export const noteOrderSeed = "clinpax-notes-v1";

export const notesByConsultation = [
  {
    "consultationId": "day1_consultation01",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": "Subjective:\n• Diarrhea for the last 3 days, affecting day-to-day activities.\n• Loose and watery stools, going to the toilet 6-7 times a day.\n• Lower abdominal pain on the left side, described as cramp-like, comes and goes.\n• Felt weak and shaky, no fever but felt hot at symptom onset.\n• Vomited at the start of symptoms, now stopped, no blood in vomit.\n• Loss of appetite, able to hold down fluids, mainly consuming soup and smoothies.\n• Had takeaway from a Chinese restaurant 4 days ago; no one else in the family has similar symptoms.\n• Generally fit and well, with well-controlled asthma; no other medications.\n\nObjective:\n• No vitals/exam findings documented in transcript.\n\nAssessment:\n• Working impression: gastroenteritis likely due to recent takeaway, given symptoms of diarrhea, abdominal pain, and vomiting.\n\nPlan:\n• Conservative management: stay hydrated, consider Dyralyte for electrolyte replenishment.\n• Take paracetamol for weakness and fever if needed.\n• Advise taking 2-3 days off work to rest.\n• Follow-up in 3-4 days if symptoms do not improve; may need stool sample testing if ongoing."
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": "Subjective:\nDiarrhoea for 3 days with loose, watery stools\nFrequency 6-7 times daily\nLower abdominal pain, left-sided, cramping in nature, intermittent\nWeakness and shakiness\nInitial fever 3-4 days ago (subjective, not measured)\nVomiting at symptom onset, now resolved\nLoss of appetite, maintaining fluid intake\nDiet restricted to soups, smoothies, liquid foods\nChinese takeaway 4 days ago at restaurant\nOne child with vomiting but no diarrhoea\nSymptoms affecting daily activities, requiring proximity to toilet\nWorking as accountant, continuing work despite symptoms\n\nPast Medical History:\nAsthma, well controlled on inhaler\nNo other bowel problems\n\nObjective:\n\nAssessment:\nGastroenteritis\n\nPlan:\nConservative management recommended\nNo antibiotics required at this stage\nMaintain hydration with fluids\nDioralyte from pharmacy for electrolyte replacement\nParacetamol 2 tablets up to 4 times daily for fever and weakness\nTime off work for 2-3 days\nReturn if symptoms persist beyond 3-4 days for further assessment including stool sample\nRest and supportive care"
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": "Presenting Problem(s):\n\nAcute gastroenteritis\n- Diarrhoea x 3 days, loose watery stools 6-7 times daily\n- Left lower abdominal cramping pain, intermittent\n- Vomiting at symptom onset, now resolved\n- Subjective fever at onset (not measured)\n- Weakness, feeling shaky\n- Anorexia, tolerating fluids and light foods (soups, smoothies)\n- Takeaway meal (Chinese restaurant) 4 days prior to symptom onset\n- 1 child with vomiting only, no diarrhoea\n- No blood in stool or vomit\n- No radiation of pain\n- Symptoms impacting work attendance\n\nPast Medical History:\n- Asthma, well controlled on inhaler\n\nSocial History:\n- Lives with wife and 2 children\n- Works in accounts, attended work during illness\n- Non-smoker\n- No alcohol\n\nImpression:\n- Acute gastroenteritis, likely viral, possible food-borne illness\n\nPlan:\n- Conservative management: oral hydration, rest\n- Dioralyte from pharmacy for electrolyte replacement\n- Paracetamol 1g QID PRN for fever/malaise\n- 2-3 days off work advised\n- Review if symptoms persist beyond 3-4 days\n- Stool sample for culture if symptoms ongoing"
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": "Consult Summary\nReview for a 3-day history of diarrhoea, vomiting, and abdominal pain, consistent with gastroenteritis. Advised on conservative management and work absence.\n\nProblem List:\nGastroenteritis:\n- 3/7 history of loose, watery diarrhoea (6-7 times/day) and intermittent, cramping left lower abdominal pain.\n- Associated with weakness, shakiness, and subjective fever at onset.\n- Vomited at the start of symptoms, but this has now ceased. No haematemesis.\n- No blood in stool.\n- Anorexia, but maintaining fluid intake (soups, smoothies).\n- Possible trigger: Chinese takeaway 4/7 ago. One child had vomiting but no diarrhoea.\n- Differential diagnosis: Viral or bacterial gastroenteritis.\n\nPast Medical History:\n- Asthma (well-controlled)\n\nMedications:\n- Inhaler for asthma (unspecified)\n\nSocial History:\n- Works as an accountant.\n- Lives with wife and two children.\n- Non-smoker.\n- Non-drinker.\n\nPlan:\n- Advised conservative management: maintain hydration (oral rehydration solutions like Dioralyte suggested), light diet.\n- Recommended paracetamol for fever and discomfort.\n- Advised to take 2-3 days off work.\n- Safety-netted: to return for review in 3-4 days if symptoms do not improve, for consideration of further investigations such as a stool sample."
      }
    ]
  },
  {
    "consultationId": "day1_consultation02",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": "Presenting Problem(s):\n\nPruritic rash x 4 days\n- Distribution: chest, hands, inner arms\n- Severe pruritus, disrupting sleep and work concentration\n- Skin dry and cracked in areas\n- No bleeding, discharge, or purulence\n- Worse than previous eczema episodes\n- Previous eczema limited to arms, responded to topical steroids and emollients\n- OTC steroid cream purchased yesterday - no improvement\n- Antihistamines trialled - ineffective\n- No identified triggers (no new soaps, detergents, clothing, or exposures)\n- Unable to participate in hiking due to discomfort\n- Daily showers for symptom relief\n- No fever, cough, dyspnoea, bowel or urinary symptoms\n\nPast Medical History:\n- Eczema (previous episodes, arms only)\n- Asthma (childhood, resolved)\n\nSocial History:\n- Lives with flatmates\n- Works full-time at pharmaceutical company\n- Occasional alcohol (few beers socially)\n- Non-smoker\n\nImpression:\n- Eczema flare\n\nPlan:\n- Prescription topical steroid (stronger than OTC preparation)\n- Emollients for bath/shower use\n- Trial fexofenadine for pruritus\n- Use treatments for 7-10 days\n- Keep trigger diary (soaps, detergents, clothing)\n- Review in 1 week if no improvement"
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": "Consult Summary\n31-year-old male presenting with a 4-day history of a widespread, pruritic rash consistent with an eczema flare. Plan is for topical steroids, emollients, and stronger antihistamines.\n\nProblem List:\nEczema Flare\n- 4/7 history of sore, red, pruritic rash on chest, hands, and antecubital fossae.\n- Described as cracked in some areas, but no bleeding or discharge.\n- Severe pruritus, disrupting sleep and concentration at work. Interfering with recreational activities (hiking).\n- Past history of eczema, previously managed with creams and shower products. Current symptoms are more widespread than previous flares.\n- Self-treatment with OTC steroid cream and antihistamines has been ineffective.\n- No identifiable triggers (e.g., new soaps, clothing).\n- No associated fever, cough, or changes in bowel/urinary habits.\n- Differential diagnosis: Eczema flare.\n\nPast Medical History:\n- Eczema\n- Asthma (in the past, not current)\n\nSocial History:\n- Age: 31\n- Occupation: Project manager at a pharmaceutical company.\n- Lives with flatmates.\n- Non-smoker.\n- Alcohol: A few beers per week.\n\nPlan:\n- Prescribe stronger topical steroid.\n- Prescribe emollients for use in bath/shower.\n- Prescribe fexofenadine for pruritus.\n- Advised to keep a trigger diary.\n- Review in 1/52 if no improvement."
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": "Subjective:\n• Presenting concern: itchy, sore, red skin on chest, hands, and arms for 4 days.\n• Key associated symptoms: cracked skin, no bleeding or pus, no fever, no cough, no breathing difficulties.\n• PMH: history of eczema, previously treated with cream; no current medications or allergies; lives with flatmates, works full-time as a project manager.\n\nObjective:\n• No vitals/exam findings documented in transcript.\n\nAssessment:\n• Working impression: possible flare-up of eczema due to similar symptoms and history; uncertainty regarding the exact cause due to lack of examination.\n\nPlan:\n• Prescribe stronger topical steroid and emollients for moisturizing skin.\n• Recommend antihistamines (loratadine or piracetamol) for itch relief.\n• Use emollients for 7 to 10 days before reassessing effectiveness."
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": "Subjective:\nPresents with a sore, red, and intensely pruritic rash for the last four days.\nThe rash is located on the chest, hands, and antecubital fossae. No facial involvement.\nThe pruritus is severe, causing sleep disturbance and impacting concentration at work.\nSelf-management includes daily showers to alleviate itching. Has tried an over-the-counter steroid cream without relief. Has also tried antihistamines recently with no benefit.\nThe current symptoms are more widespread than a previous episode of eczema, which was primarily on the arms.\nThe rash is affecting ability to participate in hobbies such as hiking.\nAssociated symptoms include soreness and cracked skin. Denies any bleeding or purulent discharge. No fever, cough, or breathing difficulties reported.\n\nPast Medical History:\nHistory of eczema, previously treated with topical steroids and emollients.\nHistory of asthma, now resolved.\nNo other medical problems.\nNo known drug allergies.\nSocial history: Works as a project manager in a pharmaceutical company. Lives with flatmates. Non-smoker. Consumes a few beers per week.\n\nObjective:\nPhysical examination findings: Rash appears consistent with eczema. Dry and cracked skin noted.\n\nAssessment:\nSuspected eczema flare.\n\nPlan:\nRecommendations and counselling: Advised to keep a diary of potential triggers such as soaps, shower gels, or clothing. Counselled on the importance of regular use of emollients for the first 7-10 days.\nTreatment planned: Prescribed a stronger topical steroid cream. Prescribed fexofenadine for pruritus. Advised to use emollients in the bath and shower.\nOther actions such as referrals or follow-up: Follow-up in one week if symptoms do not improve."
      }
    ]
  },
  {
    "consultationId": "day1_consultation03",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": "Subjective:\n• Headache since midday, located on the left side, described as throbbing, making patient feel ill and nauseous.\n• Noticed zigzag lines in vision and blurred vision before headache onset; sensitivity to bright lights.\n• Vomited twice earlier today; no fever or rash reported.\n• No prior history of migraines, but similar headache experienced a few weeks ago.\n• Patient reports high stress at work in the fashion industry; lives alone; does not smoke or drink alcohol.\n\nObjective:\n• No vitals/exam findings documented in transcript.\n\nAssessment:\n• Working impression of migraine-type headache based on unilateral throbbing pain, nausea, and light sensitivity.\n• Concern for more serious conditions such as brain cancer or meningitis is lessened due to absence of neurological deficits.\n\nPlan:\n• Recommend keeping a headache diary to identify triggers.\n• Advise strong painkillers such as paracetamol or cocodamol, and anti-inflammatories.\n• No follow-up timing explicitly stated; safety-netting not indicated."
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": "Consult Summary\nNew onset left-sided throbbing headache with visual aura, nausea and vomiting, consistent with migraine. Reassurance provided regarding concerns of brain cancer, and management plan initiated.\n\nProblem List:\nHeadache\n- Sudden onset left-sided throbbing headache since midday today.\n- Preceded by visual aura (zigzag lines, blurred vision in both eyes).\n- Associated with nausea, two episodes of vomiting, and photophobia.\n- Worsened by movement (leaning forward, head/neck movement).\n- Second similar episode in the last month; previous episode lasted a couple of days and required rest and analgesia.\n- Expressed significant concern about brain cancer, prompted by a friend's mother's recent death.\n- No fevers, skin rashes, speech disturbance, limb weakness/numbness, or balance issues. No recent head injury.\n- Differential diagnosis: Migraine with aura.\n\nMedications\n- Microgynon (for contraception, commenced 3/12 ago).\n\nFamily History\n- Mother: Migraines, hypothyroidism.\n\nSocial History\n- Works in the fashion industry, reports high levels of stress at work.\n- Lives alone.\n- Non-smoker.\n- No alcohol intake.\n- No regular exercise.\n\nPlan:\n- Commence a headache diary to identify triggers.\n- Advised analgesia for acute management (paracetamol, co-codamol, ibuprofen, naproxen).\n- Discussed potential for prophylactic medication if headaches become more persistent.\n- Safety-netted to return if symptoms worsen, do not respond to medication, or if new neurological symptoms develop (worsening neck pain, limb weakness, visual changes).\n- F/U next week to review progress."
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": "Presenting Problem(s):\n\nAcute Left-Sided Headache\n- Onset: midday today (07/06/2026), sudden\n- Location: left side, non-radiating\n- Character: throbbing\n- Severity: severe, causing nausea\n- Aggravating factors: movement, head/neck movement, leaning forward\n- Associated symptoms: visual aura (zigzag lines preceding headache), bilateral blurred vision, photophobia (wearing sunglasses), nausea with vomiting x2 today\n- Pertinent negatives: no fever, no rash, no speech disturbance, no limb weakness/numbness, no balance/coordination problems, no head trauma, no respiratory symptoms\n- Similar episode few weeks ago, lasted 2 days, resolved with analgesia and rest, required 6 days off work\n- Not prone to headaches previously\n- Patient concern: brain cancer (friend's mother recently died of brain tumour)\n\nFamily History:\n- Maternal history of migraines\n- Maternal history of hypothyroidism\n\nCurrent Medications & Allergies:\n- Rigevidon (combined oral contraceptive pill) for 3 months, for contraception\n- Allergies: not discussed\n\nSocial History:\n- Works in fashion industry\n- High work stress, pressure from management\n- Lives alone\n- No regular exercise\n- No stress management strategies\n- Non-smoker\n- Minimal alcohol intake\n\nImpression:\n- Migraine with aura\n\nPlan:\n- Headache diary to identify triggers\n- Analgesia: paracetamol, codeine, ibuprofen or naproxen\n- Discussion of prophylactic medication if headaches become more persistent\n- Review in 1 week\n- Safety netting: return immediately if headache worsening despite analgesia, worsening neck pain, limb weakness, or visual deterioration\n- Discussion regarding combined oral contraceptive pill deferred to next visit"
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": "Subjective:\nSevere headache left-sided since midday, associated with nausea and vomiting\nThrobbing pain, worse with movement (leaning forward, head/neck movement)\nVisual aura: zigzag lines in vision preceding headache onset, bilateral blurred vision\nPhotophobia: wearing sunglasses, light sensitivity\nVomited twice earlier today\nSimilar episode few weeks ago lasting couple of days, required analgesia and bed rest\nWorks in fashion industry, currently off work due to symptoms\nSignificant anxiety regarding potential brain cancer diagnosis\nFriend's mother recently died from brain tumour\nNo fever, no rash\nNo speech difficulties, no limb weakness, no balance problems\nNo recent head trauma or falls\n\nPast Medical History:\nNo previous migraine diagnosis\nFamily history: maternal migraines and underactive thyroid\nMedications: Microgynon (contraceptive) for 3 months\nSocial history: lives alone, works in fashion industry with current stressors\nNon-smoker, minimal alcohol consumption\nNo regular exercise routine\n\nObjective:\n\nAssessment:\nLikely migraine headache\n\nPlan:\nHeadache diary recommended to identify triggers\nAnalgesia: paracetamol, co-codamol, ibuprofen, naproxen\nSafety netting: return if symptoms worsen over next 2-3 days, persistent headache not responding to treatment, developing neck pain, limb weakness, or visual changes\nConsider prophylactic medication if headaches become more persistent\nFollow-up next week"
      }
    ]
  },
  {
    "consultationId": "day1_consultation04",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": "Consult Summary\nReview for a 4-day history of upper respiratory tract symptoms, likely viral in origin. Advised on symptomatic management and safety netting.\n\nProblem List:\nUpper Respiratory Tract Infection:\n- 4/7 history of feeling unwell.\n- Initial symptoms of sore throat (now resolving) and clear rhinorrhoea with nasal congestion.\n- Developed a constant, dry cough since yesterday.\n- Associated symptoms: night sweats, fatigue, intermittent generalised headache, myalgia, and dyspnoea on exertion.\n- Reports initial fever, now settled with paracetamol and ibuprofen.\n- Denies chest pain, haemoptysis, ear pain/discharge, visual changes, photophobia, nausea, vomiting, or skin rash.\n- Bowels and urine normal. Appetite slightly reduced, increased fluid intake.\n- Possible sick contact with a colleague at work.\n- Differential diagnosis: Viral URTI, Influenza.\n\nMedications\n- Paracetamol PRN\n- Ibuprofen PRN\n\nAllergies\n- No known drug allergies.\n\nPast Medical History:\n- Nil significant.\n\nFamily History:\n- Paternal grandmother: T2DM\n- Great-grandfather: Eczema\n\nSocial History\n- Accountant, reports current work period is stressful.\n- Occasional smoker at social events.\n- Occasional social alcohol consumption.\n\nPlan:\n- Advised on symptomatic management with rest and hydration.\n- Continue paracetamol and ibuprofen as needed.\n- Recommended taking time off work.\n- Safety netted: advised to return for review if symptoms worsen, particularly with high fever, worsening dyspnoea, or chest pain.\n- Follow-up if not improving by next week."
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": "Presenting Problem(s):\n\nUpper respiratory tract infection\n- Onset 4 days ago with sore throat and rhinorrhoea\n- Sore throat initially severe with odynophagia, now resolving\n- Clear nasal discharge, nasal congestion\n- Dry cough started yesterday, constant throughout day\n- Night sweats x 3-4 days\n- Initial fever, now resolved with paracetamol and ibuprofen\n- Myalgia x 2 days\n- Intermittent headaches\n- Dyspnoea on exertion, nil at rest\n- Reduced appetite\n- Increased fluid intake\n- No chest pain, nausea, vomiting, or rash\n- No otalgia, otorrhoea, or aural fullness\n- No photophobia\n- Bowels and urine normal\n- Likely exposure from colleague with similar symptoms\n\nFamily History:\n- Grandmother: type 2 diabetes\n\nSocial History:\n- Lives alone\n- Accountant, currently busy work period\n- Occasional social cigar smoking\n\nImpression:\n- Viral upper respiratory tract infection vs early influenza\n\nPlan:\n- Rest, take 1-2 days off work\n- Maintain hydration\n- Continue paracetamol and ibuprofen as needed\n- Review if not improved in 1 week\n- Return earlier if high fever, worsening dyspnoea, or chest pain develops"
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": "Subjective:\n• Feeling unwell for the past 4 days, started with sore throat and runny nose, now developing a dry cough.\n• Sore throat was painful, especially when swallowing; runny nose is clear with congestion.\n• Cough started recently, constant but not painful; experiencing night sweats and feeling tired.\n• Had some fever initially, now settling; taking paracetamol and ibuprofen for relief.\n• No chest pain, but feels winded on exertion; no ear pain or discharge; headaches present intermittently.\n• Appetite slightly decreased; no rashes or significant muscle/joint pain reported.\n• Lives alone, works as an accountant; work is affected slightly due to illness but enjoys the job.\n\nObjective:\n• No vitals/exam findings documented in transcript.\n\nAssessment:\n• Working impression: likely viral upper respiratory tract infection or early signs of flu, given the symptoms and duration.\n\nPlan:\n• Monitor symptoms; typically resolves in 7 to 10 days.\n• Safety-netting: if fever with rigors, confusion, or severe breathlessness occurs, attend ED urgently."
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": "Subjective:\nFeeling unwell for the past four days with sore throat, runny nose, and cough.\nSore throat started first, quite painful for a couple of days, now improving. Painful swallowing for one day.\nRunny nose with clear discharge and nasal congestion.\nDry cough started yesterday, constant throughout the day, not painful.\nNight sweats for the past three to four days causing tiredness and sleep disturbance.\nInitial fever, now settling with paracetamol and ibuprofen.\nShortness of breath on exertion, no chest pain.\nGeneral headaches, intermittent.\nMuscle and joint pain started in the past couple of days.\nReduced appetite, drinking more than usual.\nWork slightly affected, feeling a bit slower due to end-of-year stress.\n\nPast Medical History:\nOtherwise fit and well, no current medical problems or treatments.\nNo known drug allergies.\nFamily history: grandmother with type 2 diabetes, great grandfather with eczema.\nSocial history: lives alone, works as an accountant, occasional social smoking at company parties, occasional alcohol consumption.\n\nAssessment:\nLikely viral upper respiratory tract infection or early influenza.\n\nPlan:\nRest and time off work for one to two days.\nMaintain adequate fluid intake.\nContinue paracetamol or ibuprofen for symptom relief.\nReturn if symptoms persist beyond next week or if develops high fever, worsening breathing difficulties, or chest pain.\nAdvised to seek earlier review if condition deteriorates."
      }
    ]
  },
  {
    "consultationId": "day1_consultation05",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": "Consult Summary\nPresentation with lower abdominal pain, urinary symptoms, and subjective fever for 2/7. Commenced on empirical antibiotics for a presumed UTI.\n\nProblem List:\nLower Abdominal Pain\n- 2/7 history of gradual onset, progressively worsening lower abdominal pain.\n- Located below the umbilicus, described as a constant, burning pain.\n- Associated with mild nausea, feeling hot and sweaty (subjective fever).\n- No vomiting.\n- Bowel movements are normal; recent constipation has resolved.\n- Urinary symptoms: increased frequency, pink-coloured urine (possible haematuria). No dysuria.\n- Gynaecological history:\n- Sexually active with one partner. Last sexual contact 4/7 ago.\n- Last STI screen normal 6/12 ago.\n- Uses Implanon NXT, inserted 1 year ago. Still has periods.\n- LMP 2/52 ago. Possibility of pregnancy considered low but not excluded.\n- Systems review: No SOB, cough, palpitations, headaches, or visual disturbances.\n- Differential diagnosis: UTI, gynaecological cause, gastrointestinal cause, possible pregnancy-related issue.\n\nPast Medical History:\n- Nil significant. No surgical history.\n\nMedications:\n- Implanon NXT\n\nSocial History:\n- Works as an accountant.\n- Lives in a share house.\n- Non-smoker.\n- Social alcohol intake.\n\nPlan:\n- Commence empirical antibiotics for presumed UTI: Trimethoprim 300mg, one tablet BD for 3/7.\n- Advised to take paracetamol for pain relief.\n- Encouraged fluid intake.\n- Safety-netted to return if symptoms worsen (worsening pain, high fever, vomiting) or do not improve.\n- Advised to perform a home pregnancy test.\n- Script for Trimethoprim sent to pharmacy."
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": "Subjective:\n• Patient reports lower abdominal pain that started about 2 days ago, described as a burning pain, constant, and worsening.\n• Patient has experienced hot and sweaty sensations, slight nausea, and noticed pink urine but no burning or stinging during urination.\n• Bowel movements are normal after a period of constipation last week; no diarrhea reported.\n• Patient is sexually active with the same partner and has an Implanon contraceptive device; last period was 2 weeks ago.\n• No significant past medical history or surgeries; no medications other than Implanon.\n\nObjective:\n• No vitals/exam findings documented in transcript.\n\nAssessment:\n• Working impression: Possible urinary tract issue or gynecological concern given abdominal pain, pink urine, and nausea; further evaluation needed.\n• Uncertainty regarding potential pregnancy and the cause of symptoms due to lack of examination and testing data.\n\nPlan:\n• Consider pregnancy test to rule out pregnancy.\n• Monitor symptoms and advise to seek help if symptoms worsen or new symptoms arise.\n• No specific follow-up timing discussed."
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": "Presenting Problem(s):\n\nLower abdominal pain\n- Onset 2 days ago, gradual worsening\n- Location: suprapubic, below umbilicus\n- Character: burning, constant\n- Tender to palpation\n- No radiation\n- Functional but aware of pain constantly\n- Associated symptoms: feeling hot and sweaty, mild nausea\n- No vomiting\n- Urinary frequency\n- Pink-tinged urine, no haematuria confirmed\n- No dysuria or burning on micturition\n- Bowels: constipation last week, now resolved, normal bowel movements\n- No diarrhoea or loose stools\n- No fever measured\n- No respiratory symptoms, cough, or dyspnoea\n- No palpitations\n- No headache or visual disturbance\n- Sexual history: sexually active, single partner, last intercourse 4 days ago, cervical screening 6 months ago normal\n- Contraception: Implanon inserted 1 year ago\n- LMP: 2-3 weeks ago\n- No barrier contraception used\n- Pregnancy unlikely but not excluded\n- Never experienced similar symptoms previously\n\nSocial History:\n- Lives in share house with 2 roommates\n- Occupation: accountant\n- Non-smoker\n- Alcohol: social drinker\n\nImpression:\n- Lower abdominal pain, likely urinary tract infection\n- Pregnancy to be excluded\n\nPlan:\n- Pregnancy test to exclude pregnancy\n- Empirical antibiotic treatment: Trimethoprim 300mg PO BD for 3 days\n- Paracetamol PRN for pain\n- Increase fluid intake\n- Cranberry juice\n- Return if symptoms worsen or fail to improve\n- Red flags discussed: worsening abdominal pain, persistent fever, vomiting\n- Script sent to pharmacy"
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": "Subjective:\nLower abdominal pain, below umbilicus, burning quality, constant and worsening over 2 days\nAssociated hot and sweaty feeling\nMild nausea, no vomiting\nPink urine noted, no dysuria, increased frequency but attributed to increased fluid intake\nPrevious constipation last week, now resolved\nNo diarrhoea or loose stools\nNo measured fever\nNo chest symptoms, shortness of breath, cough, palpitations, headaches or visual problems\n\nPast Medical History:\nNo previous surgical history\nNo regular medications except Implanon inserted 1 year ago\nLast menstrual period 2 weeks ago\nSexually active with same partner, last sexual contact 4 days ago\nLast STD screen normal 6 months ago\nNo other sexual partners since\nNo smoking\nSocial alcohol consumption\nWorks as accountant\nLives in shared house with 2 roommates\nNo similar symptoms previously\n\nObjective:\n\nAssessment:\nDifferential diagnosis includes urinary tract infection, gastrointestinal cause, pregnancy-related cause\n\nPlan:\nTrimethoprim 1 tablet twice daily for 3 days\nParacetamol for pain relief\nIncrease fluid intake\nCranberry juice\nPregnancy test to be considered\nReturn if symptoms worsen or no improvement in few days\nMonitor for worsening abdominal pain, fever, vomiting"
      }
    ]
  },
  {
    "consultationId": "day1_consultation06",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": "Consult Summary\nReview for worsening shortness of breath and bilateral ankle oedema over two weeks, concerning for a heart failure exacerbation. Plan to increase frusemide, arrange bloods and an echocardiogram, with review in one week.\n\nProblem List:\nHeart Failure Exacerbation:\n- Presents with progressively worsening shortness of breath over the last 2/52, becoming more pronounced in the last 2/7.\n- Now breathless on minimal exertion (e.g., walking around the house), previously able to walk to the shops without issue.\n- Associated symptoms include a dry cough, feeling \"run down\", and new bilateral ankle oedema for the past few days.\n- Pertinent negatives: denies chest pain, palpitations, fevers. Appetite and urination are normal.\n- Differential diagnosis: Heart failure exacerbation.\n- Examination findings mentioned: Chest clear, normal saturations and blood pressure.\n\nPast Medical History:\n- Congestive Heart Failure (CHF)\n- Myocardial Infarction (\"small heart attack\") 5 years ago.\n- Osteoporosis (Mother)\n\nMedications:\n- Frusemide (dose unknown)\n- Aspirin\n- Metoprolol\n- Simvastatin\n\nAllergies:\n- No known drug allergies.\n\nFamily History:\n- Father: Died of a heart attack in his early 60s.\n- Mother: Osteoporosis.\n\nSocial History:\n- Lives alone with two cats.\n- Works part-time as a lorry driver (day shifts only).\n- Ex-smoker: 1 pack/day for 25 years (25-pack-year history), quit.\n- Alcohol: Non-drinker.\n- Exercise: Tries to walk to the shops daily.\n\nPlan:\n- Increase Frusemide to one tablet BD for a few days.\n- Arrange blood tests (FBC, U&E).\n- Refer for an echocardiogram.\n- Review in 1/52.\n- Advised to seek urgent review if symptoms worsen (increased SOB, chest pain, palpitations, dizziness)."
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": "Subjective:\n• Patient reports shortness of breath worsening over the last couple of weeks, particularly troublesome in the last few days.\n• Experiences breathlessness with minimal exertion, including at home; has a dry cough that is not troublesome.\n• Reports feeling weak and lethargic, with swollen ankles noted over the last few days; no chest pain, palpitations, or fever.\n• Past medical history includes heart failure and a small heart attack five years ago; currently takes furosemide, aspirin, and metoprolol; no known allergies.\n• Lives alone, works part-time as a lorry driver, and used to smoke a pack a day for 25 years but quit; does not drink alcohol.\n\nObjective:\n• No vitals/exam findings documented in transcript.\n\nAssessment:\n• Working impression of a potential flare-up of heart failure given the patient's symptoms of increased breathlessness and ankle swelling.\n\nPlan:\n• Increase furosemide to 2 tablets daily for the first week.\n• Arrange for blood tests to check full blood count and kidney function.\n• Organize an echocardiogram to assess heart function.\n• Schedule follow-up in one week to evaluate progress.\n• If symptoms worsen, such as increased breathlessness, chest pain, or palpitations, patient should call sooner."
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": "Presenting Problem(s):\n\nDyspnoea\n- Progressive SOB over 2 weeks, worse last few days\n- Previously able to walk to shops without difficulty, now requires rest breaks\n- Breathless at rest in house\n- Dry cough, not troublesome\n- Bilateral ankle oedema noted last few days\n- Similar symptoms during previous heart failure exacerbation\n- No chest pain\n- No palpitations\n- No fever\n- Appetite maintained\n- Urinary frequency noted, on diuretic\n- Feeling run down\n\nPast Medical History:\n- Heart failure\n- Myocardial infarction 5 years ago (hospitalised few days, recovered)\n\nCurrent Medications & Allergies:\n- Furosemide (dose unknown)\n- Aspirin\n- Omeprazole\n- Simvastatin\n- No known allergies\n\nFamily History:\n- Father died of MI in early 60s\n- Mother has osteoporosis, alive\n\nSocial History:\n- Lives alone with 2 cats (Ollie and Tim)\n- Part-time lorry driver, day shifts only\n- Concerned about impact of illness on work capacity\n- Ex-smoker: 1 pack/day x 25 years, quit\n- No alcohol\n- Exercise: walks to shops daily (now limited by SOB)\n\nExamination:\n- Chest examination - WNL\n- Oxygen saturations - WNL\n- BP - WNL\n\nImpression:\n- Acute exacerbation of heart failure\n\nPlan:\n- Increase furosemide to 1 tablet BD\n- FBC to assess for anaemia\n- U&Es to assess renal function\n- Arrange echocardiogram (1-2 weeks)\n- Review in 1 week\n- Advised to contact sooner if worsening SOB, chest pain, palpitations, or dizziness"
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": "Subjective:\nShortness of breath over last couple of weeks, worsening over last few days\nPreviously able to walk to shops without difficulty, now requires sitting down to catch breath\nBreathlessness on minimal exertion around house\nDry cough, not particularly troublesome\nBilateral ankle swelling noticed over last few days\nFeeling rundown but otherwise normal\nNo chest pain, palpitations, or fever\nAppetite and fluid intake normal\nUrinary frequency noted, attributed to diuretic medication\n\nPast Medical History:\nHeart failure diagnosed some time ago, initially responded well to treatment\nSmall heart attack approximately 5 years ago with chest pain, hospitalised for few days, recovered well since\nNo other significant medical history\nMedications: furosemide (dose unknown), aspirin, metoprolol, simvastatin\nNo known drug allergies\nFamily history: father died of heart attack in early sixties, mother has osteoporosis (still living)\nSocial history: lives alone with two cats, works part-time as lorry driver (day shifts only), ex-smoker (25 years, one pack daily, stopped), no alcohol consumption, walks to shops daily for exercise\n\nObjective:\nChest examination performed\nOxygen saturations and blood pressure normal\n\nAssessment:\nLikely heart failure exacerbation\n\nPlan:\nIncrease furosemide to two tablets daily for first few days then one tablet twice daily\nBlood tests arranged: full blood count, kidney function\nEchocardiogram organised (may take 1-2 weeks)\nFollow-up appointment in one week\nSafety netting advice given: contact sooner if symptoms worsen, chest pain, palpitations, or dizziness develop"
      }
    ]
  },
  {
    "consultationId": "day1_consultation07",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": "Subjective:\nReports feeling unwell for several days with cough, cold symptoms, and general malaise\nDry cough, worse in mornings, not productive of sputum\nNasal congestion with rhinorrhoea\nSore throat, no visible white spots or significant erythema on self-examination\nMild ear discomfort, no significant hearing loss beyond age-related changes\nShortness of breath without chest pain\nIntermittent feverish episodes with night sweats\nInitial diarrhoea on first day, now resolved\nGeneralised stiffness affecting elbows and knees, worse with bending\nSymptoms commenced Saturday evening (approximately 5 days ago) following dinner at restaurant\nNo recent travel or known food exposures\n\nPast Medical History:\nType 2 diabetes mellitus on metformin\nHypertension on lisinopril\nOccasional aspirin use\nNo known drug allergies\nWorks in steel manufacturing factory\nAlcohol consumption: approximately 9 pints beer weekly\nSmoking: occasional cigarettes, using vapouriser to reduce consumption\nLives with wife, children have left home\n\nObjective:\nAudible nasal congestion during consultation\n\nAssessment:\nViral upper respiratory tract infection\n\nPlan:\nConservative management with rest and increased fluid intake\nParacetamol for fever and discomfort\nDelayed antibiotic prescription (amoxicillin 1 tablet three times daily) to commence if symptoms persist beyond 24-48 hours or worsen\nReturn if symptoms not improving by next week"
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": "Subjective:\n• Patient reports feeling unwell for the past 5 days, with symptoms including a mostly dry cough, sore throat, runny nose, and shortness of breath.\n• Patient experiences temperature fluctuations, feeling hot and cold, and had a brief episode of diarrhea that has resolved.\n• Appetite is reported as being okay.\n• Patient has a history of type 2 diabetes and high blood pressure; currently taking metformin and lisinopril.\n• No known allergies; lives with wife, no children at home; drinks approximately 9 pints of beer weekly and occasionally smokes but is trying to quit.\n\nObjective:\n• No vitals/exam findings documented in transcript.\n\nAssessment:\n• Working impression: Viral illness, possibly early signs of flu, given the symptoms and duration.\n• Uncertainty regarding the need for antibiotics due to shortness of breath and lack of definitive signs of a chest infection.\n\nPlan:\n• Advise rest, hydration, and regular paracetamol for symptom relief.\n• Provide a prescription for amoxicillin to be used if symptoms do not improve in 24 to 48 hours.\n• Follow up next week if symptoms persist or worsen."
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": "Presenting Problem(s):\n\nUpper respiratory tract infection\n- Onset 4-5 days ago (Saturday)\n- Dry cough, worse in morning, productive of phlegm\n- Nasal congestion\n- Sore throat (patient attributes partly to shouting at football)\n- Subjective fevers, night sweats\n- Myalgia - generalised stiffness in elbows and knees\n- Shortness of breath\n- Diarrhoea on first day, resolved\n- Appetite maintained, adequate fluid intake\n- No chest pain\n- No nausea or vomiting\n- No abdominal pain\n- No ear pain or blocked ears\n- No recent travel\n- Wife recently promoted, attended restaurant celebration prior to symptom onset\n\nCurrent Medications & Allergies:\n- Metformin (dose not specified)\n- Lisinopril (dose not specified)\n- Aspirin PRN\n- NKDA\n\nSocial History:\n- Lives with wife, children have left home\n- Works at steel parts manufacturing factory\n- Alcohol: 9 pints beer per week\n- Smoking: occasional, transitioning to vaping\n\nImpression:\n- Viral illness, possible influenza\n\nPlan:\n- Conservative management: rest, adequate hydration\n- Regular paracetamol for fever\n- Delayed antibiotic prescription (amoxicillin 1 tablet TDS) to commence if no improvement in 24-48 hours\n- Review if not improved in 1 week"
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": "Consult Summary\n50-year-old male presenting with a 5-day history of URTI symptoms. Assessed via telehealth, likely viral illness. Provided with a delayed script for amoxicillin.\n\nProblem List:\nUpper Respiratory Tract Infection\n- 5/7 history of symptoms, started Saturday.\n- Symptoms include:\n- Mostly dry cough, slightly productive in the morning.\n- Rhinorrhea, sore throat, hoarse voice.\n- Subjective fevers, feeling hot and cold.\n- Mild ear blockage/dullness.\n- Myalgia and arthralgia (stiffness in elbows and knees).\n- Mild shortness of breath.\n- Diarrhoea on the first day, now resolved.\n- Denies chest pain.\n- Appetite is maintained, good fluid intake.\n- Differential diagnosis: Viral illness vs. influenza vs. early chest infection.\n\nChronic Disease Management\n- Type 2 Diabetes Mellitus:\n- On metformin.\n- Hypertension:\n- On lisinopril.\n- Previously noted to have high BP.\n\nMedications\n- Metformin\n- Lisinopril\n- Aspirin PRN\n\nAllergies\n- No known drug allergies.\n\nPast Medical History:\n- Type 2 Diabetes Mellitus\n- Hypertension\n\nSocial History\n- Lives with wife, children have left home.\n- Works in a factory manufacturing steel parts.\n- Smoker, currently cutting down by using a vape.\n- Alcohol: ~9 pints of beer per week.\n\nPlan:\n- Advised rest and increased fluid intake.\n- Advised paracetamol for fevers.\n- Issued a delayed script for Amoxicillin 1 tablet TDS, to be commenced in 24-48 hours if symptoms worsen or do not improve.\n- Advised to re-consult next week if not improving."
      }
    ]
  },
  {
    "consultationId": "day1_consultation08",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": "Consult Summary\nNew presentation of a dry, itchy rash on arms and hands for several days, possibly triggered by swimming. Diagnosed as dermatitis and managed with topical treatments.\n\nProblem List:\nDermatitis:\n- Onset of dry, itchy, red rash on arms and hands for the past few days.\n- Symptoms started after going swimming.\n- Using coconut butter with no relief.\n- No broken skin, soreness, bleeding, or discharge.\n- No spread to chest, legs, or face.\n- Reports feeling tired and stressed from work as a teacher.\n- Systems review: No fevers, vomiting, diarrhoea, or urinary symptoms. Normal appetite and bowel movements.\n- Differential diagnosis: Contact dermatitis.\n\nMedications\n- Microgynon\n\nAllergies\n- Lactose intolerance\n\nPast Medical History:\n- No history of skin conditions like eczema or dermatitis.\n\nFamily History\n- Father: Asthma\n- Mother: Hay fever\n\nSocial History\n- Lives alone.\n- Non-smoker.\n- No alcohol or recreational drug use.\n- Works as a primary school teacher, reports recent work-related stress.\n\nPlan:\n- Commence topical steroid cream and emollients.\n- Provide patient information leaflet on dermatitis.\n- Advised paracetamol/painkillers would not be helpful.\n- Review in 1/52 if symptoms do not improve."
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": "Subjective:\nReports dry, itchy skin on arms and hands for past few days\nSkin appears red, no cracked skin or spots noted\nSymptoms started after swimming a few days ago\nNo previous episodes of similar skin problems\nWork stress as primary school teacher, children being disruptive\nIncreased walking recently\nUsing coconut butter for past few days without improvement\nNo fever, sweating, or other systemic symptoms\nReports feeling tired but otherwise well\nEating and drinking normally, appetite fine\nNo bowel problems, vomiting, or loose stools\nUrine normal\n\nPast Medical History:\nCurrently taking Microgynon (contraceptive pill)\nLactose intolerant\nNo previous skin problems, eczema, or dermatitis\nNo known drug allergies\nFamily history: father with asthma, mother with hay fever\nNo family history of skin problems\nLives alone, non-smoker, no alcohol or recreational drugs\n\nObjective:\n\nAssessment:\nLikely dermatitis\n\nPlan:\nSteroid cream for inflammation\nEmollients for dry skin application throughout day\nOver-the-counter antihistamines for itchiness\nPatient information leaflet provided about dermatitis\nReview in one week if symptoms persist or worsen"
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": "Presenting Problem(s):\n\nDermatitis\n- Dry, itchy skin x few days, bilateral arms and hands\n- Erythematous, no vesicles\n- Onset after swimming\n- No prior episodes\n- No spread to chest/legs/face\n- No cracked skin, bleeding, or discharge\n- Coconut butter applied - no improvement\n- Associated with work stress (teacher)\n- No fever\n- Fatigue present\n- Appetite and fluid intake normal\n- Bowel and bladder function normal\n\nCurrent Medications & Allergies:\n- Microgynon (combined oral contraceptive pill)\n- Lactose intolerance\n\nFamily History:\n- Father: asthma\n- Mother: allergic rhinitis\n\nSocial History:\n- Occupation: primary school teacher\n- Non-smoker\n- No alcohol use\n- No recreational drug use\n\nImpression:\n- Dermatitis (likely irritant contact dermatitis post-swimming exposure)\n\nPlan:\n- Topical corticosteroid cream for inflammation\n- Emollient cream for dry skin, apply throughout day\n- Loratadine PRN for pruritus\n- Patient education leaflet provided\n- Review in 1 week if no improvement"
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": "Subjective:\n• Patient reports being stressed at work for the past few days and has developed dry, itchy skin on arms and hands.\n• Symptoms started a few days ago after swimming; skin is red and itchy, with no spots, fever, or sweating.\n• No previous history of skin problems; currently taking Mikrofon (contraceptive pill); lactose intolerant.\n• Family history includes father with asthma and mother with hay fever; lives alone, does not smoke or drink alcohol.\n\nObjective:\n• No vitals/exam findings documented in transcript.\n\nAssessment:\n• Working impression: Possible dermatitis, likely triggered by swimming, given the sudden onset and associated symptoms.\n\nPlan:\n• Recommend steroid creams for inflammation and emollients for dry skin; patient can also try over-the-counter antihistamines for itchiness.\n• Advise follow-up in one week if symptoms do not improve."
      }
    ]
  },
  {
    "consultationId": "day1_consultation09",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": "Consult Summary\n19-year-old female presenting with a 3-day history of dysuria, suprapubic pain and haematuria, consistent with a simple UTI.\n\nProblem List:\nUrinary Symptoms:\n- 3/7 history of stinging pain on urination.\n- Associated with lower abdominal cramping pain.\n- Noted a small amount of haematuria today.\n- Reports malodorous urine.\n- No change in urinary frequency.\n- No fevers, nausea, vomiting, or flank pain.\n- No vaginal discharge.\n- Tried over-the-counter bicarbonate with no relief.\n- Differential diagnosis: Simple urinary tract infection.\n\nPast Medical History:\n- Irritable Bowel Syndrome (IBS).\n\nAllergies:\n- Clindamycin (causes swelling).\n\nSocial History:\n- University student (Biology).\n- Lives in a flat with friends.\n- Non-smoker.\n- Drinks alcohol socially on weekends.\n- Sexually active with one male partner for 2/12, uses condoms for contraception.\n- Last menstrual period was 2/52 ago.\n- Has never had an STI screen.\n\nPlan:\n- Commence antibiotics for simple UTI (Nitrofurantoin or Trimethoprim) for 3/7.\n- Advise increased fluid intake, can try cranberry juice.\n- Safety net advice: to return if symptoms do not improve by the end of the week, or sooner if developing fever, back pain, or feeling more unwell.\n- Advised to avoid sexual intercourse until symptoms resolve."
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": "Subjective:\n• Presenting concern: burning pain when urinating for the past few days, with associated cramping pain in the lower abdomen.\n• Key associated symptoms: a little bit of blood in urine earlier today, urine has a weird smell; no fever, nausea, vomiting, diarrhea, or loose stools reported.\n• Past medical history: history of IBS; no current medications; allergic to clindamycin with swelling as a reaction.\n\nObjective:\n• No vitals/exam findings documented in transcript.\n\nAssessment:\n• Working impression: likely urinary tract infection (UTI) based on symptoms of burning pain during urination and abdominal cramping.\n\nPlan:\n• Prescribe a 3-day course of antibiotics (nitrofurantoin or trimethoprim), 1 tablet twice a day.\n• Advise increased fluid intake to help flush the infection; cranberry juice may help with symptoms.\n• Follow up if symptoms do not improve by the end of the week or if new symptoms develop.\n• If fever with rigors, confusion, mottled skin, severe breathlessness → attend ED urgently; maintain hydration; seek help if passing very little urine."
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": "Subjective:\nDysuria for 3 days with stinging pain during micturition\nAssociated lower abdominal cramping pain, described as different from menstrual cramps\nHaematuria noted earlier today\nUrine has unusual odour\nNo increased urinary frequency\nNo fever or back pain\nNo nausea, vomiting, or diarrhoea\nSexually active with regular partner for 2 months\nUses condoms for contraception\nLast menstrual period couple weeks ago\nNo vaginal discharge\n\nPast Medical History:\nIBS\nNo other significant medical problems\nAllergy to clindamycin causing swelling\nNo regular medications\nTried over-the-counter bicarbonate without benefit\nNo previous STD screening\nLives in flat near college with friends\nBiology student\nNon-smoker, social alcohol consumption on weekends\nNo family history of renal, bladder, or bowel disease\n\nObjective:\n\nAssessment:\nLikely simple urinary tract infection\n\nPlan:\nNitrofurantoin or trimethoprim one tablet twice daily for 3 days\nIncrease fluid intake to help flush infection\nConsider cranberry juice for symptomatic relief\nAvoid sexual intercourse while symptoms persist\nContinue barrier contraception\nReturn if symptoms persist beyond this week or develop fever, back pain, or general malaise\nPregnancy test advised if symptoms do not improve"
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": "Presenting Problem(s):\n\nDysuria\n- Burning pain on urination x 3 days\n- Lower abdominal cramping (different from menstrual cramps)\n- Haematuria noted earlier today\n- Offensive-smelling urine\n- No increased urinary frequency\n- No fever\n- No flank pain\n- No nausea or vomiting\n- Bowels normal, no diarrhoea\n- Sexually active with regular partner x 2 months, uses condoms\n- No vaginal discharge\n- Last menstrual period 2 weeks ago\n- Not pregnant\n- History of IBS\n- Tried over-the-counter bicarbonate without relief\n- Never had STI screening\n\nCurrent Medications & Allergies:\n- Clindamycin allergy - swelling\n\nSocial History:\n- Lives in flat near college with friends\n- University student studying biology\n- Non-smoker\n- Social alcohol use on weekends\n\nImpression:\n- Simple UTI\n\nPlan:\n- Nitrofurantoin or trimethoprim 1 tablet BD for 3 days\n- Increase fluid intake\n- Consider cranberry juice\n- Advise temporary sexual abstinence until symptoms resolve\n- Continue barrier contraception\n- Return if symptoms persist after 3 days or if develops fever, back pain, or worsening symptoms\n- Pregnancy test if symptoms persist"
      }
    ]
  },
  {
    "consultationId": "day1_consultation10",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": "Subjective:\n• Patient is a 19-year-old female presenting with burning pain during urination and increased frequency for just under a week.\n• Noticed pink discoloration in urine today.\n• Reports crampy, achy pain in the lower abdomen, worse when urinating.\n• Denies nausea, vomiting, fever, or changes in bowel habits apart from known IBS.\n• Currently sexually active with a long-term boyfriend, uses combined oral contraceptive pill.\n• Last unprotected sex was 1-2 weeks ago; last period was 2 weeks ago.\n• Smoked weed for the first time a week and a half ago; drinks alcohol socially.\n• Allergic to clindamycin.\n\nObjective:\n• No vitals/exam findings documented in transcript.\n\nAssessment:\n• Working impression: likely UTI or cystitis based on symptoms of dysuria and abdominal pain, with no red flags such as fever or back pain.\n\nPlan:\n• Discussed treatment options with antibiotics: trimethoprim or nitrofurantoin.\n• Safety-netting advised: if symptoms worsen or do not improve, seek further medical attention."
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": "Presenting Problem(s):\n\nDysuria\n- Burning/stinging on urination x 1 week\n- Urinary frequency, interfering with university attendance\n- Pink-tinged urine noted today\n- Suprapubic discomfort, achy, worse with voiding\n- No fever, nausea, vomiting, flank pain, or radiation\n- No vaginal discharge\n- Sexually active with long-term partner, combined oral contraceptive pill, no barrier contraception\n- Last menstrual period 2 weeks ago\n- No haematuria (frank blood)\n\nPast Medical History:\n- IBS - variable bowel frequency and consistency, no new symptoms\n\nCurrent Medications & Allergies:\n- Combined oral contraceptive pill\n- Mebeverine for IBS\n- Allergy: Clindamycin (reaction not specified)\n\nSocial History:\n- University student, studying English, first year\n- Lives in university halls with flatmate\n- Family lives outside London\n- Non-smoker\n- Occasional social alcohol use\n- Cannabis use once 1.5 weeks ago at party (first time)\n\nImpression:\n- Uncomplicated UTI/cystitis\n\nPlan:\n- Trimethoprim or nitrofurantoin 3-day course to be prescribed\n- Mid-stream urine sample to be collected and sent to laboratory\n- Maintain adequate hydration\n- Simple analgesia for pain relief\n- Return if symptoms persist beyond 1 week\n- Safety netting: return immediately if fever, back pain, or vomiting develop\n- Follow up for urine culture results"
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": "Subjective:\nDysuria and urinary frequency for approximately one week\nBurning, stinging sensation when passing urine\nSuprapubic pain, described as achy, worse during micturition\nHaematuria noted today (pink urine)\nSymptoms affecting university attendance due to frequent toilet visits\nNo nausea, vomiting, fever, or back pain\nBowel movements unchanged from baseline IBS pattern\nNo unusual vaginal discharge\nSexually active with long-term boyfriend, no condom use\nLast menstrual period two weeks ago\nFirst-time cannabis use approximately one and a half weeks ago at social gathering\n\nPast Medical History:\nIBS with variable bowel habits\nCombined oral contraceptive pill\nMebeverine for IBS-related cramping\nClindamycin allergy (reaction occurred couple of years ago)\nLives in university halls with flatmate\nEnglish student, course progressing well\nOccasional social alcohol consumption\nNo regular smoking\n\nObjective:\n\nAssessment:\nLikely urinary tract infection/cystitis\n\nPlan:\nUrine sample for microscopy, culture and sensitivity\nAntibiotic therapy: trimethoprim or nitrofurantoin three-day course\nAdequate fluid intake recommended\nParacetamol for symptomatic pain relief\nReturn if symptoms persist or worsen\nAdvised to seek urgent review if fever, back pain, or vomiting develop\nCounselled regarding cannabis avoidance for general health"
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": "Consult Summary\n19-year-old female presenting with a one-week history of dysuria, urinary frequency, and suprapubic pain, consistent with a urinary tract infection. Plan for antibiotics and urine MCS.\n\nProblem List:\nUrinary Tract Infection:\n- Presents with a <1/52 history of dysuria (burning/stinging), urinary frequency, and suprapubic ache, worse on micturition.\n- Noticed pink-tinged urine today.\n- No fevers, nausea, vomiting, or flank pain.\n- No unusual vaginal discharge.\n- Sexually active with a long-term partner, uses combined oral contraceptive pill. Last menstrual period 2/52 ago. Unprotected intercourse (no condoms) 1-2/52 ago.\n- Differential diagnosis: Uncomplicated cystitis.\n\nIrritable Bowel Syndrome:\n- Known history of IBS.\n- Variable bowel habits, alternating between soft and hard stools.\n- No recent change in bowel habits associated with current urinary symptoms.\n- Takes Mebeverine for cramps.\n\nMedications:\n- Combined oral contraceptive pill\n- Mebeverine\n\nAllergies:\n- Clindamycin\n\nPast Medical History:\n- Irritable Bowel Syndrome (IBS)\n\nSocial History:\n- University student (English), living in halls with a flatmate.\n- Non-smoker.\n- Occasional social alcohol use.\n- Reports first-time cannabis use 1.5/52 ago at a party. Expresses no intention to use regularly.\n\nPlan:\n- Provide urine sample pot for MSU to be sent for MCS.\n- Commence empirical antibiotics (Trimethoprim or Nitrofurantoin) for 3 days.\n- Advised on simple analgesia (paracetamol) and maintaining hydration.\n- Safety-netted to return if symptoms worsen or if fevers, back pain, or vomiting develop.\n- Follow up if symptoms do not improve."
      }
    ]
  },
  {
    "consultationId": "day1_consultation11",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day1_consultation12",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day1_consultation13",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day1_consultation14",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day1_consultation15",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day2_consultation01",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day2_consultation02",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day2_consultation03",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day2_consultation04",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day2_consultation05",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day2_consultation06",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day2_consultation07",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day2_consultation08",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day2_consultation09",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day2_consultation10",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day3_consultation01",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day3_consultation02",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day3_consultation03",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day3_consultation04",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day3_consultation05",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day3_consultation06",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day3_consultation07",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day3_consultation08",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day3_consultation09",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day3_consultation10",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day4_consultation01",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day4_consultation02",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day4_consultation03",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day4_consultation04",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day4_consultation05",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day4_consultation06",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day4_consultation07",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day4_consultation08",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day4_consultation09",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day4_consultation10",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day5_consultation01",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day5_consultation02",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day5_consultation03",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day5_consultation04",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day5_consultation05",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day5_consultation06",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day5_consultation07",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day5_consultation08",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day5_consultation09",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day5_consultation10",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day5_consultation11",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  },
  {
    "consultationId": "day5_consultation12",
    "notes": [
      {
        "id": "note-a",
        "label": "Note A",
        "text": ""
      },
      {
        "id": "note-b",
        "label": "Note B",
        "text": ""
      },
      {
        "id": "note-c",
        "label": "Note C",
        "text": ""
      },
      {
        "id": "note-d",
        "label": "Note D",
        "text": ""
      }
    ]
  }
] as const satisfies readonly NotesForConsultation[];
