import hashlib
import json
import random
from pathlib import Path

import openpyxl


ROOT = Path(__file__).resolve().parents[1]
WORKBOOK_PATH = ROOT / "source_data.xlsx"
OUTPUT_PATH = ROOT / "lib" / "notes-data.ts"
SOURCE_KEY_PATH = ROOT / "private" / "note-source-key.json"
SOURCES = ["Clinpax", "Heidi", "MBSPro", "Lyrebird"]
NOTE_IDS = ["note-a", "note-b", "note-c", "note-d"]
NOTE_LABELS = ["Note A", "Note B", "Note C", "Note D"]
SEED_VERSION = "clinpax-notes-v1"


def stable_shuffle(items, consult_id):
    digest = hashlib.sha256(f"{SEED_VERSION}:{consult_id}".encode("utf-8")).hexdigest()
    rng = random.Random(int(digest[:16], 16))
    shuffled = list(items)
    rng.shuffle(shuffled)
    return shuffled


def read_source_notes():
    workbook = openpyxl.load_workbook(WORKBOOK_PATH, read_only=True, data_only=True)
    source_notes = {}

    for source in SOURCES:
        sheet = workbook[source]
        rows = sheet.iter_rows(values_only=True)
        headers = list(next(rows))
        consult_index = headers.index("consult_id")
        note_index = headers.index("soap_note")

        for row in rows:
            if not row or not row[consult_index]:
                continue

            consult_id = str(row[consult_index]).strip()
            note_text = "" if row[note_index] is None else str(row[note_index]).strip()
            source_notes.setdefault(consult_id, {})[source] = note_text

    return source_notes


def main():
    source_notes = read_source_notes()
    consultations = []
    source_key = {}

    for consult_id in sorted(source_notes):
        ordered_sources = stable_shuffle(SOURCES, consult_id)
        source_key[consult_id] = dict(zip(NOTE_IDS, ordered_sources))
        notes = []

        for index, source in enumerate(ordered_sources):
            notes.append(
                {
                    "id": NOTE_IDS[index],
                    "label": NOTE_LABELS[index],
                    "text": source_notes[consult_id].get(source, ""),
                }
            )

        consultations.append({"consultationId": consult_id, "notes": notes})

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    source = (
        "/* This file is generated by scripts/generate-notes-data.py. */\n\n"
        'import type { NotesForConsultation } from "./notes";\n\n'
        f"export const noteOrderSeed = {json.dumps(SEED_VERSION)};\n\n"
        "export const notesByConsultation = "
        f"{json.dumps(consultations, indent=2, ensure_ascii=False)} as const "
        "satisfies readonly NotesForConsultation[];\n"
    )
    OUTPUT_PATH.write_text(source, encoding="utf-8")
    SOURCE_KEY_PATH.parent.mkdir(parents=True, exist_ok=True)
    SOURCE_KEY_PATH.write_text(
        json.dumps(
            {
                "seed": SEED_VERSION,
                "description": (
                    "Private blinded note mapping. Do not commit or deploy; "
                    "this reveals which source generated each blinded note."
                ),
                "mapping": source_key,
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    empty_count = sum(
        1
        for consultation in consultations
        for note in consultation["notes"]
        if not note["text"]
    )
    print(
        f"Generated notes for {len(consultations)} consultations "
        f"({empty_count} blank note slots)."
    )
    print(f"Saved private source key to {SOURCE_KEY_PATH}")


if __name__ == "__main__":
    main()
